apiVersion: v1
kind: Config
preferences: {}
users:
- name: dev
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - eu-west-1
      - eks
      - get-token
      - --cluster-name
      - green-dev
      - --output
      - json
      command: aws
- name: prod
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - eu-west-1
      - eks
      - get-token
      - --cluster-name
      - green-prod
      - --output
      - json
      command: aws
      env:
      - name: AWS_PROFILE
        value: elliptic-production
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJY29mZ2ViT2JmbGt3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBNU1ERXdPVFF3TkRsYUZ3MHpOVEE0TXpBd09UUTFORGxhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUR3cmwzRFNxbUhvVGR5WDFpR3UybFo1MWFhQjJncFpoWURjajhQL0NGTzBrZVJQTUt4R3lvYm00TWQKS01Za1JFL3hCbmRVdElKOThmc3E4QlhFTzVuQUJMRyszd29jcGI0L0FLTDJKNytGWlZ5b1B3ZnlqTStNd2ZKVwpKdG9lVDMyRGZtMm1hWVNQNFVDS3JMRFBkZ1VKZCsyS2xoYjM5aDU2VWhVY3BaT2N1eVlBdW5vUHZjak5BV091CmZuNnlCS1FVaWkwSkZLNXlRTWFGMytpSllpZGFZRVRXa3VWRFpWMklONW5PUTlVT0NDYW9ZTWo2cFBOOUxyWSsKQ0xwY0pjbW42cHo1eW1jL1hmZWFraEFLK3B1Y3RrTWtoWDJqM0xrQnZ0SjBPVHhSSnFqa3hWdWtvanFOR2pCVApqNFJNZnR4K0JQTERHaGg3NVVxNFJialcrcm5qQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRVmc3ai9FS1NKMWFxekxJTHlmYTIyc2VVQ1FEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ1ZPbGVudWsvVworTm5TU2cwWVdreVVMN2dRQmg4VEt6Z0hCTDhLYVMzOGJ5SHZXWHR3UGtpVDlLdHpuTnlTVVVZS1haNENXTXhICkdwM0JRMUYzc21GdisyVjlqYndyOTgrb0hwWi9wdkhBMHNSQlpvNEVlTThLcS8rQnJZR0dwUUxqVUpWR3NmODkKcGJrUWdTWnhCMFFiVWd4N08zVXpZd0gycm0wOFlRbWxTeTNMUnFPcnpkaTA2M2V4WUVFV3V5NXNKdDQvckF3cwpPQW1nRmxpaUxZczZldkQ3WFZUS1pXMk9UbWtzUHQ4ZStDa0RpUTc0eUtKaHN0UUJxTHNZZUpsZ01RbVlvQWVICjRUZWlNU3FhYUpIMy90T2pxb0ttcnFyTlBvSHNOTXkxMW9aT0QxaTN5OHo0OXlqRFFTVmQvTU1yVW9tUXBJS2gKTXl5RGt1cnFYQlk3Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://651CD19C25B6178C7CE6A2C819C0FB42.gr7.eu-west-1.eks.amazonaws.com
  name: green-dev
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJYUswV2FPRTZXaU13RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFd01ERXdPVFUxTkRCYUZ3MHpOVEE1TWpreE1EQXdOREJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURLSTdXYUJsbWZKRE9OQ2hwWWROSXBZYjNXMFl1a2ZDb3ZVODZodFF3T3NvSzJzQytHSjhNWWU1VTkKa1JCQTZjc25IMDAva0NMOHFsWVJGQTFZN1dHdENNd1Mwa3M2TGdxZkUzZ0dLMEpIN0I0WDRWOVhIWDAwWUNLSApDanZSZmdVcDNMWnUzVnFLRElONWNiNzlQZFZXWGtvN0dJSmIwWlBEay9OblcxYkxncXVBVnQxWHE0RUM0RjVSCktUSnpVL2szYzZKRWpuOUtLWHIxd1pibEFwOU9QN2crZjNDNHNJaGU0RDgrNGRiZkNpbVI1S2F3amJLb3BVbmgKWXFHYXhlZi9vZFBxRHhXSE5EWExqRVU3Q3RHOWxQQy9KaTM0ay9HU2ErMERySGEvUE9JMkNRRnBaTHlLbWQrQgpicFlxOE4zUHBMbFpQeXVsWmtYYW1wZTFBQUpOQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTdFd3UWl5UXFNcm02MW5wdzVML2VudEd4WTVEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ0ZVc09CY2VxYwo1UTVzb25IUktKU054ZXRJZEg2Vms4SUdZSW9LOGxvV01MSmdzN09jelF3ZXN6YWlnVzRGdExiVjZJeXJxZDBtCjZBZHJRak1YTzFpYTNlS0VZNTJUbDNiVzhNQVAxRHJnbENGaWZaWFh6OFFRL0V3TUJCVjBTVkVaOEF1andFMXcKOXREQUQ3YkU2NmlQSWp1TVQrS3Q1eGhBUFM4YlFSOE5uem12V2NsTU9CSlZqbEhsMFY0UGJVR2FMR0hSbUpYbwp3TmNHSU1HUEJGRVpVVFl3Sm4vc1phTjltYnpkdGhhcklubXBBT1JSbEMra2tNcVJnbFd1WUptZnEzcStZNVpMClVyZVFlZDcrYVpFR0lXS3ZGSjFwcUMza211dlcxQ01lYUxJTmhmWnBMN2diNXpSU1NtN1RrcHZ0MVFMM1Y4WVgKRkFXNlNtdUNtZnFRCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://8916703ED4F5F81AB5A5553A6890CF54.gr7.eu-west-1.eks.amazonaws.com
  name: green-prod
contexts:
- name: dev
  context:
    cluster: green-dev
    user: dev
- name: prod
  context:
    cluster: green-prod
    user: prod

